### ISSUE TITLE
Sometimes get `Invalid client serial`

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/ashpd#16] opened 2021-07-31 06:43 UTC
It is very hard to reproduce as it happens very rarely. Although, it is reproducible from the demo through screencast by creating a session. (Haven't tested other)

The log shows the following:
`** (process:43167): WARNING **: 14:41:02.960: Invalid client serial`

The process 43167, according to system monitor, is `xdg-dbus-proxy`.

I'll add some additional information, ill try to debug

**Comment by bilelmoussaoui** [comment] 2021-07-31 06:46
That looks like an issue on the portal side probably

**Comment by SeaDve** [comment] 2021-07-31 06:49
could it be the randomizer from window identifier?

**Comment by bilelmoussaoui** [comment] 2021-07-31 07:20
> could it be the randomizer from session handle?

No I don't think so, the handle is correctly validated per dbus types définitions

**Comment by SeaDve** [comment] 2021-08-02 09:38
after a long time, i was able to reproduce it again. The CreateSession calls succeeded, then the warning occurs. I think it may not had received the response from SelectSources

**Comment by bilelmoussaoui** [comment] 2021-08-02 12:04
That doesn't help, as I can't reproduce it here. Maybe the portal crashed ? Nothing obvious on the logs ? From the other sides as well. E.g, xdg-desktop-portal/xdg-desktop-portal-gtk?

**Comment by SeaDve** [comment] 2021-08-04 09:12
I'll try to get more info when I am able to reproduce it again

**Comment by SeaDve** [comment] 2021-08-09 01:27
was able to reproduce again, I checked on journalctl logs of the xdg-desktop-portal and xdg-desktop-portal-gtk. I didn't see anything relevant. (I'm not sure though if im looking at the right place)

**Comment by bilelmoussaoui** [comment] 2022-01-20 10:08
I will go ahead and close this, I don't see anything that could cause this from ashpd side

**Closed by bilelmoussaoui** 2022-01-20 10:08 UTC

**Comment by A6GibKm** [comment] 2023-10-14 16:06
The actual issue is https://github.com/flatpak/xdg-dbus-proxy/issues/46.
